In [2]:
import numpy as np

In [3]:
#1#arange()
list1 = np.arange(3*3)
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
#2#reshape()
list1 = list1.reshape(3,3)
list1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
#3#sort()
np.sort(list1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.sort(list1, axis=None)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
list1 = np.arange(1,10).reshape(3,3)
list1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
#4#array
list2 = np.array=([1,2,3],
                 [4,5,6],
                 [7,9,8])
np.sort(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
#5#concatenate()
list3 = np.concatenate((list1, list2))

In [130]:
#6#ndim()
list3.ndim

2

In [52]:
#7#size()
list3.size

18

In [55]:
#8#shape()
print(list3)
list3.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 9 8]]


(6, 3)

In [57]:
#9#hstack()
np.hstack((list1, list2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 9, 8]])

In [60]:
#10#vstack()
list4 = np.vstack((list1, list2))
list4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 9, 8]])

In [63]:
list5 = np.sort(list4, axis=None)
list5

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [75]:
#11#hsplit()
list6 = np.hsplit(list5, 3)
list6

[array([1, 1, 2, 2, 3, 3]),
 array([4, 4, 5, 5, 6, 6]),
 array([7, 7, 8, 8, 9, 9])]

In [78]:
#12#min()
np.sort(list6, axis=None).min()

1

In [79]:
#13#max()
np.sort(list6, axis=None).max()

9

In [80]:
#14#sum()
np.sort(list6, axis=None).sum()

90

In [112]:
#15#ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [113]:
#16#zeros()
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [117]:
#17#random.rand()
random_num1 = np.random.rand(3, 4)
random_num1

array([[0.8642415 , 0.30415095, 0.93280235, 0.17808311],
       [0.80348183, 0.71656492, 0.95954228, 0.68468947],
       [0.09524001, 0.59634691, 0.66163585, 0.60398832]])

In [118]:
#18#transpose()
random_num1.transpose()

array([[0.8642415 , 0.80348183, 0.09524001],
       [0.30415095, 0.71656492, 0.59634691],
       [0.93280235, 0.95954228, 0.66163585],
       [0.17808311, 0.68468947, 0.60398832]])

In [131]:
#19#flip()
print(random_num1)
print("\nflip it!!!")
print(np.flip(random_num1))
print("\nHere You Go....")

[[0.8642415  0.30415095 0.93280235 0.17808311]
 [0.80348183 0.71656492 0.95954228 0.68468947]
 [0.09524001 0.59634691 0.66163585 0.60398832]]

flip it!!!
[[0.60398832 0.66163585 0.59634691 0.09524001]
 [0.68468947 0.95954228 0.71656492 0.80348183]
 [0.17808311 0.93280235 0.30415095 0.8642415 ]]

Here You Go....


In [152]:
#20#save
np.save('random34',random_num1)

In [173]:
#21#load
random_num34 = np.load('random34.npy')
random_num34

array([[0.8642415 , 0.30415095, 0.93280235, 0.17808311],
       [0.80348183, 0.71656492, 0.95954228, 0.68468947],
       [0.09524001, 0.59634691, 0.66163585, 0.60398832]])

In [9]:
#22#savetxt
list7 = [1,2,3,4,5,6,7,8,9]
np.savetxt('list7.csv', list7)

In [10]:
#23#loadtxt
list7_csv = np.loadtxt('list7.csv')
print(list7_csv)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [12]:
#24#copy()
list8 = list7.copy()
list8

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
#25#choose()
choices = [[0, 1, 2, 3], 
           [10, 11, 12, 13],
           [20, 21, 22, 23], 
           [30, 31, 32, 33]]
np.choose([2, 3, 1, 0], choices)

array([20, 31, 12,  3])

In [20]:
#26#compress()
a = np.array([[1, 2], [3, 4], [5, 6]])
print(np.compress([0, 1], a, axis=0))
print("-------")
print(np.compress([False, True], a, axis=1))


[[3 4]]
-------
[[2]
 [4]
 [6]]


In [22]:
#27#cumprod()#cumulative product
a = np.array([1,2,3,4])
np.cumprod(a)

array([ 1,  2,  6, 24], dtype=int32)

In [25]:
#28#cumsum#cumulative sum
a = np.array([1,2,3,4,5,6])
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [28]:
#29#inner() product of vectors
a = np.array([1,2,3])
b = np.array([2,2,2])
np.inner(a, b)

12

In [46]:
#30#fill() fill all elements with given value
a = np.array([3, 2])
a.fill(5)
a

array([5, 5])

In [49]:
#32#empty() create empty array container
a = np.empty(5)
a.fill(7)
print(a)


[7. 7. 7. 7. 7.]


In [50]:
#33#imag()#Return the imaginary part of the complex argument.
a = np.array([1+2j, 3+4j, 5+6j])
print(a.imag)
print("-----")
a.imag = np.array([8, 10, 12])
print(a)

[2. 4. 6.]
-----
[1. +8.j 3.+10.j 5.+12.j]


In [51]:
#34#prod()
np.prod([[1.,2.],[3.,4.]])

24.0

In [54]:
#35#put() put the values in positions where match
a = np.arange(5)
print(a)
np.put(a, [0, 2], [-44, -55])
print(a)

[0 1 2 3 4]
[-44   1 -55   3   4]


In [58]:
#36#putmask()#Changes elements of an array based on conditional and input values
x = np.arange(6).reshape(2, 3)
print(x)
np.putmask(x, x>2, x**2)
print("-----")
print(x)

[[0 1 2]
 [3 4 5]]
-----
[[ 0  1  2]
 [ 9 16 25]]


In [59]:
#37#real()#Return the real part of the complex argument
a = np.array([1+2j, 3+4j, 5+6j])
a.real

array([1., 3., 5.])

In [61]:
#38#cov()#Estimate a covariance matrix between variables
x = np.array([[1, 4], [2, 3], [3, 2], [4, 1]]).T
print(x)
print("-----")
np.cov(x)


[[1 2 3 4]
 [4 3 2 1]]
-----


array([[ 1.66666667, -1.66666667],
       [-1.66666667,  1.66666667]])

In [65]:
#39#mean#Compute the arithmetic mean along the given axis
a = np.arange(1,17).reshape(4,4)
print(a)
print("------")
print(np.mean(a, axis=0))
print("------")
print(np.mean(a, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
------
[ 7.  8.  9. 10.]
------
[ 2.5  6.5 10.5 14.5]


In [66]:
#40#std()#Compute the standard deviation along the specified axis
a = np.arange(1,17).reshape(4,4)
print(a)
print("------")
print(np.std(a, axis=0))
print("------")
print(np.std(a, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
------
[4.47213595 4.47213595 4.47213595 4.47213595]
------
[1.11803399 1.11803399 1.11803399 1.11803399]


In [76]:
#41#var()#Compute the variance along the specified axis
a = np.arange(1,65).reshape(8,8)
print(a)
print("------")
print(np.var(a, axis=0))
print("------")
print(np.var(a, axis=1))

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
------
[336. 336. 336. 336. 336. 336. 336. 336.]
------
[5.25 5.25 5.25 5.25 5.25 5.25 5.25 5.25]


In [86]:
#42#cross()#Return the cross product of two (arrays of) vectors
x = [1, 1, 1]
y = [1, 2, 3]
np.cross(x, y)

array([ 1, -2,  1])

In [83]:
#43#dot()#Dot product of two arrays. Specifically
x = [1, 1, 1]
y = [1, 2, 3]
np.dot(x, y)

6

In [87]:
#44#outer()#Compute the outer product of two vectors
x = np.array(['a', 'b', 'c'], dtype=object)
np.outer(x, [1, 2, 4])

array([['a', 'aa', 'aaaa'],
       ['b', 'bb', 'bbbb'],
       ['c', 'cc', 'cccc']], dtype=object)

In [88]:
#45#vdot()#Return the dot product of two vectors
x = [1, 1, 1]
y = [1, 2, 3]
np.vdot(x, y)

6

In [89]:
#46#identity()#Return the identity array
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [92]:
#47#all()#Test whether all array elements along a given axis evaluate to True
print(np.all([[True,False],[True,True]], axis=0))
print("------")
print(np.all([[True,False],[True,True]], axis=1))

[ True False]
------
[False  True]


In [93]:
#48#any()#test whether any array element along a given axis evaluates to True
print(np.any([[True,False],[True,True]], axis=0))
print("------")
print(np.any([[True,False],[True,True]], axis=1))

[ True  True]
------
[ True  True]


In [95]:
#49#Return the indices of the elements that are non-zero
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)
print("------")
print(np.nonzero(x))


[[3 0 0]
 [0 4 0]
 [5 6 0]]
------
(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))


In [96]:
#50#where()#Return elements chosen from x or y depending on condition
a = np.arange(10)
print(a)
print("------")
print(np.where(a < 5, a, 10*a))

[0 1 2 3 4 5 6 7 8 9]
------
[ 0  1  2  3  4 50 60 70 80 90]
