In [1]:
import numpy as np

In [3]:
1#arange()
list1 = np.arange(3*3)
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
2#reshape()
list1 = list1.reshape(3,3)
list1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
3#sort()
np.sort(list1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.sort(list1, axis=None)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
list1 = np.arange(1,10).reshape(3,3)
list1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
4#array
list2 = np.array=([1,2,3],
                 [4,5,6],
                 [7,9,8])
np.sort(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
5#concatenate()
list3 = np.concatenate((list1, list2))

In [130]:
6#ndim()
list3.ndim

2

In [52]:
7#size()
list3.size

18

In [55]:
8#shape()
print(list3)
list3.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 9 8]]


(6, 3)

In [57]:
9#hstack()
np.hstack((list1, list2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 9, 8]])

In [60]:
10#vstack()
list4 = np.vstack((list1, list2))
list4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 9, 8]])

In [63]:
list5 = np.sort(list4, axis=None)
list5

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [75]:
11#hsplit()
list6 = np.hsplit(list5, 3)
list6

[array([1, 1, 2, 2, 3, 3]),
 array([4, 4, 5, 5, 6, 6]),
 array([7, 7, 8, 8, 9, 9])]

In [78]:
12#min()
np.sort(list6, axis=None).min()

1

In [79]:
13#max()
np.sort(list6, axis=None).max()

9

In [80]:
14#sum()
np.sort(list6, axis=None).sum()

90

In [112]:
15#ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [113]:
16#zeros()
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [117]:
17#random.rand()
random_num1 = np.random.rand(3, 4)
random_num1

array([[0.8642415 , 0.30415095, 0.93280235, 0.17808311],
       [0.80348183, 0.71656492, 0.95954228, 0.68468947],
       [0.09524001, 0.59634691, 0.66163585, 0.60398832]])

In [118]:
18#transpose()
random_num1.transpose()

array([[0.8642415 , 0.80348183, 0.09524001],
       [0.30415095, 0.71656492, 0.59634691],
       [0.93280235, 0.95954228, 0.66163585],
       [0.17808311, 0.68468947, 0.60398832]])

In [131]:
19#flip()
print(random_num1)
print("\nflip it!!!")
print(np.flip(random_num1))
print("\nHere You Go....")

[[0.8642415  0.30415095 0.93280235 0.17808311]
 [0.80348183 0.71656492 0.95954228 0.68468947]
 [0.09524001 0.59634691 0.66163585 0.60398832]]

flip it!!!
[[0.60398832 0.66163585 0.59634691 0.09524001]
 [0.68468947 0.95954228 0.71656492 0.80348183]
 [0.17808311 0.93280235 0.30415095 0.8642415 ]]

Here You Go....


In [152]:
20#save
np.save('random34',random_num1)

In [173]:
21#load
random_num34 = np.load('random34.npy')
random_num34

array([[0.8642415 , 0.30415095, 0.93280235, 0.17808311],
       [0.80348183, 0.71656492, 0.95954228, 0.68468947],
       [0.09524001, 0.59634691, 0.66163585, 0.60398832]])

In [182]:
22#savetxt
list7 = [1,2,3,4,5,6,7,8,9]
np.savetxt('random34.csv', list6)

In [195]:
#23#loadtxt
random34_csv = np.loadtxt(('random34.csv')
print(random34_csv)

SyntaxError: invalid syntax (<ipython-input-195-aa6f1640d24d>, line 3)