# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [8]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
l1 = np.full(10, np.nan)
l1

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

3. Create a vector with values ranging from 10 to 49

In [7]:
l2 = np.arange(10,50)
l2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [8]:
l2.shape

(40,)

5. Print the type of the previous array in question 3

In [13]:
print("Type:",l2.dtype)

Type: int32


6. Print the numpy version and the configuration


In [24]:
print("NumPy Version:",np.version)

NumPy Version: <module 'numpy.version' from 'C:\\Users\\Talal\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\version.py'>


7. Print the dimension of the array in question 3


In [26]:
print("Dimension of l2:",l2.ndim)

Dimension of l2: 1


8. Create a boolean array with all the True values

In [28]:
l3 = np.ones(10, dtype=bool)
l3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [32]:
l4 = np.arange(1,10).reshape(3,3)
l4
print("l4 Dimension: ",l4.ndim)

l4 Dimension:  2


10. Create a three dimensional array



In [36]:
l5 = np.arange(1,100).reshape(-1,3,3)
print(l5)
print("-------")
print("lf Dimension:",l5.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]]

 [[46 47 48]
  [49 50 51]
  [52 53 54]]

 [[55 56 57]
  [58 59 60]
  [61 62 63]]

 [[64 65 66]
  [67 68 69]
  [70 71 72]]

 [[73 74 75]
  [76 77 78]
  [79 80 81]]

 [[82 83 84]
  [85 86 87]
  [88 89 90]]

 [[91 92 93]
  [94 95 96]
  [97 98 99]]]
-------
lf Dimension: 3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [44]:
l6 = np.arange(1,10)
print(l6)
print("Revesre:",l6[::-1])

[1 2 3 4 5 6 7 8 9]
Revesre: [9 8 7 6 5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [48]:
l7 = np.zeros(10)
l7[4] = 1
print(l7)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [54]:
l8 = np.eye(3,3)
print(l8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [57]:
l8.dtype = int
print("Dataype before:",l8.dtype)
l8.dtype = float
print(l8)
print("Data Type",l8.dtype)

Dataype before: int32
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Data Type float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [61]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arrmulp = np.multiply(arr1,arr2)
print(arrmulp)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [63]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arrgreat = arr1 > arr2
print(arrgreat)

[[ True False  True]
 [False  True False]]


17. Extract all odd numbers from arr with values(0-9)

In [70]:
arr1 = np.arange(0,10)
print(arr1)
print(arr1[~(arr1%2==0)])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [74]:
arr1 = np.where(arr1%2==0,arr1,-1)
print(arr1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [75]:
arr = np.arange(10)
arr[5:9] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [81]:
arr = np.ones((4,4))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [83]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d[1,1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [110]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
print(arr3d)


[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [118]:
arr = [np.arange(10) for i in range(2)]
print(arr[0])

[0 1 2 3 4 5 6 7 8 9]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [119]:
arr = [np.arange(10) for i in range(2)]
print(arr[1][1])

1


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

26. Create a 10x10 array with random values and find the minimum and maximum values

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [151]:
def function1():
   # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.
    
    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt = np.subtract(arr.T,brr).T# write your code here 
  
    return subt
function1()

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [ ]:
#task10
def function10():
    # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.
    
    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt = # write your code here 
  
    return subt

     """
     Expected Output:
               array([[2 2 2]
                      [2 2 2]
                      [2 2 2]])
     """ 
    